name: Deploy Frontend
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            
            # Push the image to docker hub
            - name: Docker login
              uses: docker/login-action@v2
              with: 
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}
            - name: build and push
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./docker/Dockerfile.fe
                push: true
                tags: kartikdoda/test-fe:${{github.sha}}
                
            # SSH into a vm and deploy and pull the pushed image there for be
            - name: Deploy to VM
              run: |
                 echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
                 chmod 600 ~/ssh_key
                 ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@54.89.187.89 "docker pull kartikdoda/test-fe:${{github.sha}} && docker stop test-fe || true && docker rm test-fe || true && docker run -d --name test-fe -p 3000:3000 kartikdoda/test-fe:${{github.sha}}"