name: Deploy Backend
on:
    push:
        branches: [main]
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            
            # Push the image to docker hub
            - name: Docker login
              uses: docker/login-actions@v2
              with: 
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}
            - name: build and push
              uses: docker/build-push-actions@v4
              with: 
                context: .
                file: /docker/Dockerfile.ws
                push: true
                tags: devops/test-ws:${{github.sha}}
            
            # SSH into a vm and deploy and pull the pushed image there for be